title: "DoctorWho"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2526S2-CS2103T-F10-1/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
